### ISSUE TITLE
Deletion of Lobbies 

### ISSUE THREAD

**Issue by PatSalvis** [sopra-fs22-group-01/server#103]
- [x]  Check if frontend is involved in bug
- [x] Clean deletion without breaking the code

**Comment by lsenni** [comment]
The deleteLobby Method in GameManager deletes the lobby successfully. But after the deletion, the Match can't get created (Match could not be created -> seems like a IncorrectId Exception)

**Comment by PatSalvis** [comment]
Leads to bugs
